### ISSUE TITLE
Recovery method not found for method in class that implements an interface

### ISSUE THREAD

**Issue by engineal** [spring-projects/spring-retry#197]
I have a component class that implements an interface. The interface is being autowired into my calling class, and in my implementation class I have annotated a method from the interface with `@Retryable` and added a public recovery method. However, when the retry fails, it fails to find the recovery method.

Through some debugging, I have observed that `ReflectionUtils#doWithMethods(Class, MethodCallback)` is used to iterate through the methods of the failing method's class to find the recovery method. However, in my case, `failingMethod.getDeclaringClass()` is returning my interface instead of my implementation class, and because the interface doesn't contain my recovery method, the recovery method is never found. I noticed that the object of my implementation class is passed to the `RecoverAnnotationRecoveryHandler#init(Object, Method)` method in the target parameter, but never used.

```
	private void init(Object target, Method method) {
		final Map<Class<? extends Throwable>, Method> types = new HashMap<Class<? extends Throwable>, Method>();
		final Method failingMethod = method;
		ReflectionUtils.doWithMethods(failingMethod.getDeclaringClass(),
```

Is there a reason that `failingMethod.getDeclaringClass()` is being used instead of `target.getClass()`? Thank you for looking at this issue. Let me know if I should open a PR to attempt to fix this.

Currently using Spring Retry 1.2.5.RELEASE with Spring Boot 2.2.5.RELEASE.

**Comment by dsyer** [comment]
We could certainly look at a PR for this. I expect there would be tests that fail if there was a reason to use `getDeclaringClass()` but I suppose you never know.

**Comment by garyrussell** [comment]
Isn't this fixed by https://github.com/spring-projects/spring-retry/pull/124 ?

Try 1.3.0.BUILD-SNAPSHOT.

**Comment by dsyer** [comment]
I did wonder about that. But the code quoted above is still there in master right?

**Comment by engineal** [comment]
@garyrussell Thanks for your comment. I tried out your most recent changes from #124, but unfortunately the issue still exists. I've reviewed the changes and I noticed you added the following method to the `RecoverAnnotationRecoveryHandler` class, however that method isn't being called anywhere.

```java
	private Recover findAnnotationOnTarget(Object target, Method method) {
		try {
			Method targetMethod = target.getClass().getMethod(method.getName(), method.getParameterTypes());
			return AnnotationUtils.findAnnotation(targetMethod, Recover.class);
		}
		catch (Exception e) {
			return null;
		}
	}
```
Looking at this method I think it should fix my issue if it were used to find the Recover annotation. How did you intend for this method to be called?

**Comment by dsyer** [comment]
I think that was a casualty of the merge that had to be done to resolve conflicts. I can put the call to that method back (see 4fe92bb). Can someone provide a test case?

**Comment by garyrussell** [comment]
@dsyer There already is a test here 

https://github.com/spring-projects/spring-retry/blob/4fe92bb20f4beb158b2934a34a6aa0fa1c10df8e/src/test/java/org/springframework/retry/annotation/EnableRetryTests.java#L172-L181

Which fails at line 179 when running in an IDE (with your fix backed out).

However maven reports

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

(Which is why I missed it while rebasing the PR).

But if I look further up in the log...

```
INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   EnableRetryTests.testInterface:179 » ExhaustedRetry Cannot locate recovery met...
[INFO] 
```

**Comment by engineal** [comment]
@dsyer thanks for the quick fix. I tested it out but realized it doesn't actually solve my issue.

It seems to solve the case where the `@Recover` annotation is in the subclass, but still defined in the interface. However, my issue is where the recovery method isn't defined in the interface at all.

```java
interface TheInterface {
	void service1();
}

class TheClass implements TheInterface {

	private boolean recovered;

	@Override
	@Retryable
	public void service1() {
		throw new RuntimeException("Planned");
	}

	@Recover
	public void recover(Exception e) {
		this.recovered = true;
	}

	public boolean isRecovered() {
		return this.recovered;
	}
}
```

I've tested my suggested change, replacing `failingMethod.getDeclaringClass()` with `target.getClass()`, and the PR is #199.
